### ISSUE TITLE
H2 데이터베이스 repo 추가 및 초기 구성 설정

### ISSUE THREAD

**Issue by Thirdsense3** [Thirdsense3/StudyMatcher_BE#4]
H2 데이터베이스 관련 파일들을 repo에 추가하고

 H2 초기 구성 설정들을 문서나 readme에 작성했으면 좋겠습니다.

**Comment by wooky9633** [comment]
최초 아래로 DB 파일 생성
jdbc url : jdbc:h2:~/StudyMatcher
사용자명 : StudyMatcher

이후 실행시 jdbc url만 바꿔서 실행
jdbc url : jdbc:h2:tcp://localhost/~/StudyMatcher

**Comment by Thirdsense3** [comment]
Goooood
